export const PROGRAMS = [
"Audrey Chen, Phil Minton, Henrik Munkeby Nørstebø, Thomas Rohrer, Michael Vorfeld — Medea (2016), an improvised butoh opera with Valentin Tszin, Flavia Ghisalberti, Poema Theatre, and thirty butoh dancers",
"Ian Spektor, Max Werner, Alexey Gnedenko — Noisy Intro (2022), a live electroacoustic performance",
"Uliana Horbachevska, Mark Tokar, Petras Vyšniauskas, Klaus Kugel — Ultramarine (2012), live improvisation",
"Ian Spektor — Death in June (2024), audio installation",
"Adam Mirza — Body – Process : (Ritual) (2010) for tenor saxophone",
"Agata Zubel — 3 Songs (2021) for prepared piano and voice",
"Alban Berg — Four Pieces, Op. 5 (1913) for clarinet and piano",
"Albert Saprykin — oi (2024) for double bass solo",
"Alessandro Solbiati — Concerto (2016) for guitar solo and fifteen instruments",
"Alessandro Solbiati — Insieme (2017) for ensemble",
"Alessandro Solbiati — Neve (2017) for seventeen instruments",
"Alessandro Solbiati — Quaderno d'immagini (2004–2005)",
"Alessandro Solbiati — Sinfonia da camera (2006) for fifteen instruments",
"Alexander Knaifel — Cantus Firmus (1963; rev. 2007)",
"Alexander Knaifel — Confession (2003; rev. 2009) for piano",
"Alexander Knaifel — O Heavenly King (1994), version for piano",
"Alexander Knaifel — Old Photographs (2004) for piano",
"Alexander Knaifel — Piano: Musique militaire (1964; rev. 2009)",
"Alexander Knaifel — Scar–March (1988) for radiola and piano",
"Alexander Knaifel — Tea Drinking with a Shift (2007) for grand piano",
"Alexander Knaifel — This Child (Luke 9:48) (1997), version for piano",
"Alexander Mosolov — Four Newspaper Advertisements, Op. 21 (1926, orch. by Edison Denisov) for soprano and chamber orchestra",
"Alexander Mosolov — Three Children's Scenes, Op. 18 (1926, orch. by Edison Denisov) for soprano and chamber orchestra",
"Alexander Scriabin — Vers la Flamme, Op. 72 (1914) for piano",
"Alexander Vustin — Offering (2005) for violin, viola, cello, piano, and percussion — in memory of Dmitri Shostakovich",
"Alexandra Filonenko — Shadow Play (2011) for theremin and button accordion",
"Alexey Retinsky — Dreams of the Bird (2010–2011) for violin and piano",
"Alexey Retinsky — Sleeping Music. Probability of Awakening (2011) for fixed media",
"Alexey Retinsky — Triø (2007) for violin, cello, and piano",
"Alexey Retinsky — Долго (и в той долготе - беспрерывно-внезапно) (2015)",
"Alexey Shmurak — Four Quadrae (2023) for voice, piano, harpsichord, electronics",
"Alexey Shmurak — Holy Grail (from Dark Wood cycle) (2023) for piano solo",
"Alexey Shmurak — Liebestod (2024), quadraphonic audio installation developed from Liebestod album material",
"Alexey Shmurak — Return (2012) for solo pianist, live processing, and audio playback",
"Alexey Shmurak — Seven Sonnets on Texts by Ivan Mishutin (2014) for voice and piano",
"Alexey Shmurak — Strawberry Sonata (2014) for violin and piano",
"Alexey Shmurak — TV (2011) for flute, oboe, clarinet, violin, cello, synthesizer, and tape",
"Alexey Shmurak — Weightlessness (2023) for voice, piano, harpsichord, electronics",
"Alexey Shmurak, Oleh Shpudeiko — Liebestod (2022) for voice, piano, harpsichord, and electronics, set to texts by Ivan Mazepa, Volodymyr Svidzinsky, Inger Christensen, and John Keats",
"Alexey Shmurak, Oleh Shpudeiko — Orange Songs: Sound Theatre (2016) for voice, piano, electric guitar, toy instruments and computer",
"Alexey Shmurak, Oleh Shpudeiko, with Dariia Kuzmych — The Glass Bead Game (2014), an audiovisual performance",
"Alexey Shmurak, Oleh Shpudeiko, with Vira Marchenko — Solovey (2018), multimedia performance engaging voice, speech, song, sign, space, and meditation",
"Alexey Shmurak, Oleh Shpudeiko, Mark Buloshnikov — Around Silvestrov (2017), live performance for voice, pianos and electronics",
"Alisa Zaika — \"he only dreamed of places now…\" (2022) for seven instruments",
"Alisa Zaika — Double concerto (2018) for flute and double bass",
"Alla Zagaykevych — \"Et dans un long tournoiement j'entrerai dedans l'étang céleste…\" (1996) for instrumental trio and electronics — on verses by Oleh Lysheha",
"Alla Zagaykevych — ...diving in.. waking up.. flying up.. diving deep... (2011) for solo violin and electronics",
"Alla Zagaykevych — Aerial Mechanics (2005) for instrumental ensemble",
"Alla Zagaykevych — Rana (Summer 2022)",
"Alla Zagaykevych — Signs of Presence (2021) after poems by Iya Kiva",
"Alla Zagaykevych — To Breathe (2002) for voice and electronics",
"Alvin Curran — For Cornelius (1981–1982) for piano",
"Alvin Curran — Inner City n°1 & 2 (1993–1999)",
"Amnon Wolman — Dangerous Bend (2002) for cello and electronics",
"Katya Libkind, Sasha Andrusyk, Mykhailo Bogachov, FORMA — Subsoil Assets (Korysni kopalyny): An exhibition of operas in the pavilion of memories (2021), based on recordings of operas by Salvatore Sciarrino, Carmine Emanuele Cella, and Stefano Gervasoni",
"Anastasia Sadomski — Stone (2011) for cello and piano",
"Andrei Popov — Sagebrush (2011) for theremin solo",
"Andrew Chubb — Motion One (1998) for piano",
"Andrei Popov — Suite (2013) for theremin and piano",
"Ann Rosén — Kniestulpe (1991) for violin",
"Anna Arkushyna — Spraying (2012) for five instruments",
"Anna Korsun — The Song of a Fish (2010) for soprano",
"Anonymous — The Nightingale (13th–14th c.)",
"Anonymous — Tu solus Dominus (10th–12th c.)",
"Anton Lukoszevieze — American Poets and Cello (2004) for cello and tape",
"Anton Webern — Four Pieces for Violin and Piano, Op. 7 (1910)",
"Anton Webern — Three Short Pieces for Cello and Piano, Op. 11 (1914)",
"Antonio Correa — 5 Short pieces (2013) for piano",
"Antonio Correa — Day 5 (2013) for piano",
"Antonio Correa — Surface 1 (2012) for piano",
"Antonio Politano — \"Mercè!\", grido piangendo (2011) for five voices",
"Antonio Politano — …del suono, i suoi sublimi inganni… (2017) for ensemble",
"Arnaud Desvignes — Sur une branche morte (2014) for piano",
"Arnold Schoenberg — Five Piano Pieces, Op. 23 (1923), selections",
"Arnold Schoenberg — Piano Piece, Op. 33a (1928–29)",
"Arnold Schoenberg — Six Little Piano Pieces, Op. 19 (1911)",
"Arnold Schoenberg — Suite for Piano, Op. 25 (1923), selections",
"Arnold Schoenberg — Three Piano Pieces (October 1894)",
"Arnold Schoenberg — Three Piano Pieces, Op. 11 (1909; rev. 1924)",
"Arnold Schoenberg — Verklärte Nacht (Transfigured Night), Op. 4 (1899) for string sextet",
"Arturs Maskats — Concerto Grosso (1996) for violin, cello, percussion, and string orchestra",
"Arvo Pärt — Für Alina (1976) for piano",
"Arvo Pärt — Morning Star (2007) for mixed choir a cappella",
"Arvo Pärt — Most Holy Mother of God (2003) for mixed choir a cappella",
"Arvo Pärt — Tabula Rasa (1977) for two violins, prepared piano, and string orchestra",
"Arvo Pärt — The Deer's Cry (2007) for mixed choir a cappella",
"Arvo Pärt — Variationen zur Gesundung von Arinuschka (1977) for piano",
"Arvydas Malcys — Thorny Eyes (2004) for violin, cello, and piano",
"Asmati Chibalashvili — Light (2012) for violin, cello, piano, and video",
"Audrey Chen, Henrik Munkeby Nørstebø — .AVI 3 (2015), an audiovisual improvisation with butoh dancers Flavia Ghisalberti and Valentin Tszin",
"Baudouin de Jaer — Adolf Wölfli's Musical Cryptograms (2015), lecture-concert",
"BEAMSPLITTER (Audrey Chen and Henrik Munkeby Nørstebø) — Medea in the Gardens of the Hesperides, an improvised electroacoustic performance accompanied by a visual project of Lisa Biletska",
"Bohdan Kryvopust — hOpak (2012) for piano trio",
"Bohdan Sehin — ...and, like sailors, enjoying the sight of land (2011) for ensemble",
"Bohdan Sehin — Daedalus (2010–2011) for flute, clarinet, violin, and cello",
"Boris Filanovsky — Scompositio (2014), mono-opera for voice, 13 instruments, and audio projection",
"Borys Liatoshynskyi — Mourning Prelude (1920) for piano",
"Brian Ferneyhough — Carceri d'invenzione I (1982) for ensemble",
"Bruno Maderna — Después y… (1971) for guitar solo",
"Bryce Dessner — Aheym (2009) for string quartet",
"Carlo Gesualdo — \"Mercè\" grido piangendo (1611)",
"Carlos Perón Cano — Yoga Music (2014)",
"Carmine Emanuele Cella — Ali oscillano in fioco cielo (2013)",
"Carmine Emanuele Cella — Expectations (2011) for piano",
"Carmine Emanuele Cella — La mémoire de l'eau (2014) for nine musicians",
"Carmine Emanuele Cella — Upside-Down (2004) for ensemble",
"Carmine Emmanuele Cella — Pane, Sale, Sabbia (2017), an opera to the libretto by Rossano Baronciani",
"Charlotte Seither — excerpt from Dreizehn Verwehungen (2012) for solo voice",
"Christian Mason — Heaven's Chimes are Slow (2010) for flute and piano",
"Christian Mason — Incandescence (2011) for cello",
"Christian Wolff — Exercise 5 (1973–74) for any instruments",
"Christian Wolff — Variations on Six Melodies (1961)",
"Christophe Bertrand — Scales (2008–2009) for ensemble",
"Christophe Bertrand — Yet (2002) for twenty musicians",
"Christopher Fox — Susan's Purple (1991) for cello",
"Claude Debussy — Preludes, Book I (1909–1910), Nos. I–XII for piano",
"Claudio Ambrosini — La Pupara (2013) for five voices",
"Claudio Ambrosini — Incipit (2017) for ensemble",
"Claudio Monteverdi / arr. Lucia Ronchetti — Sento un certo non so che",
"Claudio Monteverdi — Cor mio mentre vi miro (1603)",
"Claudio Monteverdi — Luci serene e chiare (1603)",
"Claudio Monteverdi — Sì, ch'io vorrei morire (1603)",
"Claus-Steffen Mahnkopf — Kammerkonzert (1995–1996) for piano and ensemble",
"Daan Jansens — …qui me réduit au silence (2017) for ensemble",
"Daan Janssens — Di me... (2005/2014)",
"Dariia Kuzmych — Map of Exit from the Body of the City (2018), mixed-media exhibition",
"David Lang — The Little Match Girl Passion (2007) for four singers playing simple percussion",
"David Toub — For Four (2012) for piano",
"Denis Johnson — November (1959) for piano",
"Denis Levaillant — Etude XIV Transe (2004) for piano",
"Denis Levaillant — une barque sur le Niger (1992) for piano",
"Dmitry Kourliandski — Voice-off / Out of Voice (2008)",
"Dmytro Pashinsky — Cosa Arcana e Stupenda (2017) for ensemble",
"Doina Rotaru — L'ange avec une seule aile (2017) for flute and ensemble",
"Douwe Eisenga — Simon Song 1 (2004)",
"Ed Sol — The Dam (June 2023), live electronics",
"Edgard Varèse — Density 21.5 (1936) for theremin",
"Edgard Varèse — Intégrales (1923–1925) for eleven wind instruments and four percussionists",
"Edgard Varèse — Intégrales (1923–1925) for small orchestra and percussion",
"Edgard Varèse — Ionisation (1929–1931) for percussion",
"Edgard Varèse — Octandre (1923) for eight instruments",
"Edison Denisov — Birdsong (1969) for piano and tape",
"Egidija Medekšaitė — Oscillum (2011) for cello",
"Elena Subach — LIMBO (2024), a pop-up exhibition",
"Elliott Carter — Canaries (1950) for four timpani",
"Elliott Carter — March (1950) for four timpani",
"Elliott Carter — Scrivo in vento (1991) for flute",
"Eric Maestri — Sto cadendo, ricado in me, scompaio… (2013)",
"Erik Griswold — Chooks! & Bicycle Lee Hooker from Old MacDonald's Yellow Submarine (2004) for toy piano, prepared piano, bicycle bell, bicycle horn, and train whistle",
"Erkki-Sven Tüür — Sonata (1985) for piano",
"Eve Beglarian — Night Psalm (1992) for piano",
"Evis Sammoutis — Sculpting Air (2013–2014) for five voices with swung tubes and harmonicas",
"Fabio Mengozzi — Reverie IV (2014) for piano",
"Fabio Mengozzi — Segreta luce (2014) for piano",
"Fausto Romitelli — Mediterraneo I - Les idoles du soleil (1992–1993) for ensemble",
"Fausto Romitelli — Mediterraneo II - L'azur des déserts (1992–1993) for voice and twelve musicians",
"Fausto Romitelli — Professor Bad Trip I–III (1998–2000) for ensemble",
"Fausto Romitelli — Trash TV Trance (2002) for electric guitar",
"Federico Costanza — Nel vortice così come nel nervo (2017) for ensemble",
"Filip Rathé — El agua y la muerte (2014), Avec diamants extrêmes (2009–2019) for ensemble",
"Filip Rathé — La fiamma vitale (2017) for ensemble",
"Florent Motsch — Luci serene e chiare (2013)",
"Florian Mosch — Litanies nocturnes (2017) for ensemble",
"Francesco Filidei — Filastrocca (2011) for piano",
"Franck C. Yeznikian — Schliere (du prisme à l'entaille) (2008) for cimbalom",
"Franco Donatoni — Hot (1989) for solo saxophone and six musicians",
"Franco Donatoni — Lem: due pezzi (1983) for double bass",
"François Couturier — The Man Who Saw The Angel (2008) for chamber orchestra",
"François Couvreur — Cosa Arcana e stupenda (2017) for ensemble",
"Frederic Lagnau — Bagatelle sans modalite (1997) for piano",
"Frederic Lagnau — Wind Mozaics (2007) for piano",
"Galina Ustvolskaya — 12 Preludes (1953) for piano",
"Galina Ustvolskaya — Sonata No. 5 (1986) for piano",
"Galina Ustvolskaya — Sonata No. 6 (1988) for piano",
"Galina Ustvolskaya — Sonata No. 2 (1949/51) for piano",
"Galina Ustvolskaya — Sonata No. 4 (1957) for piano",
"George Crumb — Vox Balaenae (1971) for amplified flute, piano, and cello",
"Ghédalia Tazartès — Coda Lunga (2012) for voice and tape",
"Giacinto Scelsi — Aitsi (1974) for amplified piano",
"Giacinto Scelsi — HÔ (1960), quattro melodie for solo soprano",
"Giacinto Scelsi — Ko-Tha (1967) for guitar",
"Giacinto Scelsi — Okanagon (1968) for harp, double bass, and tam-tam",
"Giacinto Scelsi — String Trio (1958) for violin, viola, and cello",
"Giacinto Scelsi — Taiagarù (1962), cinque invocazioni for solo soprano",
"Giacinto Scelsi — Three Latin Prayers (1972)",
"Giacinto Scelsi — Tre pezzi (1956) for tenor saxophone",
"Gianluca Deserti — Feuer (2011–12) for piano",
"Giovanni Sollima — Violoncelles, vibrez! (1993) for two cellos and string orchestra",
"Giulia Monducci — AVENUE #1 - 5 is always empty (2017) for double bass and ensemble",
"Giulia Monducci — Klangfarbenkreis (2014) for piano",
"Giya Kancheli — A little Daneliade (1996) for violin, piano and strings",
"Giya Kancheli — Abii ne Viderem (1992) for string orchestra and viola",
"Giya Kancheli — Rag-Gidon-Time (1995) for violin and button-accordion",
"Giya Kancheli — Suite from Theatre and Film Music (arr. 2012) for button accordion",
"Gordon Kampe — No Spock! (2011) for theremin, piano, and tape",
"Gregorian chant — Lilium floruit (11th–12th century)",
"Gregorian chant — Natus est Rex (11th–12th century)",
"Gregorian chant — Rachel plorans (Fleury Playbook, 12th century)",
"Gregorian chant — Veni Creator Spiritus (9th century)",
"Grigor Narekatsi — Liturgical monody (951–1003)",
"Gualtiero Dazzi — Cosa arcana (2017) for ensemble",
"Guillaume Dufay — Alma redemptoris mater (c. 1430) for three voices",
"Guillaume Dufay — Ave maris stella (c. 1430–1450) for three voices",
"Guillaume Dufay — Mirandas parit haec urbs (c. 1436) for three voices",
"Guillaume Dufay — Supremum est mortalibus (1433) for three voices",
"Guy Klucevsek — Selected works for accordion solo (2013)",
"György Kurtág — Attila József Fragments (1980–81) for solo voice",
"György Kurtág — Bagatellen, Op. 14d Nos. 1, 2, 6 (1981) for trio",
"György Kurtág — Brefs messages, op. 47 (2011) for nine instruments",
"György Kurtág — Doloroso (1990) for flute",
"György Kurtág — Eight Piano Pieces, Op. 3 (1960)",
"György Kurtág — Hommage à Berényi Ferenc 70 (1997) for cimbalom",
"György Kurtág — Magyar nyelvlecke külföldieknek",
"György Kurtág — Messages of the Late Miss R.V. Troussova, Op. 17 (1976–1980) for soprano and ensemble",
"György Kurtág — Quarrels for piano four hands",
"György Kurtág — Selections from Játékok / Games (Books I–VII; 1973–79 / ongoing), including 12 New Microludes (Book III)",
"György Kurtág — Seven Songs, Op. 22 (1982) for voice and cimbalom",
"György Kurtág — Songs to poems by Anna Akhmatova, op. 41 (1997– in progress) for soprano and ensemble",
"György Kurtág — Szálkák / Splinters, Op. 6d (1962/1978)",
"György Kurtág — Szálkák, Op. 6/c (1973)",
"György Kurtág — Tre pezzi, op. 38 (1996) for clarinet and cimbalom",
"György Kurtág — Un brin de bruyère à Witołd (1991)",
"György Kurtág — Virág az ember for piano six hands",
"György Kurtág — Vékony Ildikó: 2009 október 3 (2009)",
"György Kurtág — …quasi una fantasia... op. 27/1 (1987–1988) for piano and ensemble",
"György Ligeti — Capriccio No. 1 (1947) for piano",
"György Ligeti — Chamber concerto (1969–1970) for thirteen solo instrumentalists",
"György Ligeti — Concerto for cello and orchestra (1966)",
"György Ligeti — Concerto for piano and orchestra (1985–88)",
"György Ligeti — Nouvelles Aventures (1962–1965) for three singers and seven instruments",
"Gérard Grisey — Partiels (1975) for 18 musicians",
"Gérard Grisey — Vortex Temporum (1994–1996) for flute, clarinet, piano, violin, viola, cello",
"Hans Otte — Aus dem Buch der Stunden (From the Book of Hours) (1979–1982)",
"Hans Otte — Book of Sounds (1991–1998) for piano",
"Helena Tulve — Languse ööl (\"At the Night of Decline\") (2006/2015) for six instruments",
"Helmut Zapf — Canto dell'aria (1998) for oboe and tape",
"Hennadiy Boychenko — Going in Circles (\"Khodinnia po kolu\") (May 2023) for voice, clarinet, percussion, cello, and double bass",
"Hildegard von Bingen — De Sancta Maria (11th century)",
"Howard Skempton — Surface Tension No. 1 (1976) for trio",
"Iannis Xenakis — Epicycle (1989) for cello and ensemble",
"Iannis Xenakis — Jalons (1986) for fifteen musicians",
"Iannis Xenakis — Paille in the Wind (1992) for cello and piano",
"Iannis Xenakis — Échange (1989) for bass clarinet and ensemble",
"Igor Stravinsky — Symphonies of Wind Instruments (1920), transcription for piano by Arthur Lourié",
"Igor Stravinsky — Symphonies of wind instruments (1920), transcribed for button accordion solo by Leonid Hrabovsky (2011–2012)",
"Ihor Zavhorodnii — Lacrimosa (February 2023) for violin solo",
"Ihor Zavhorodnii — радості птахів, яких не існує (2015) for flute, clarinet, vibraphone, piano, violin, cello",
"Ihor Zavhorodnii — Cosa arcana e stupenda (2017) for ensemble",
"Nataliia Polovynka, Slovo i Holos (Word and Voice) — IRMOS. Rejoice: Chants to the Mother of God, the Chief of Chiefs (2014)",
"Iraida Yusupova — Kitezh-19 (2011) for theremin and tape",
"Ivan Fedele — Etude Australe n. 4 \"Aptenodytes\" (2003) for solo piano",
"Jaan Rääts — Autogram, Op.110 (1999), for piano",
"Jaan Rääts — Bagatelles Nos. 3, 4, 8, 15, 22, Op.50 (1973), for piano",
"Jaan Rääts — 24 Estonian Preludes, Op.80 (1988–89), for piano",
"Jaan Rääts — Marginalia Nos. 1 and 19, Op.65 (1979–80), for piano",
"Jaan Rääts — 24 Marginalia, Op.68 (1982), for two pianos",
"Jaan Rääts — Metal, Op.91 (1992), for two pianos",
"Jaan Rääts — Piano Sonata No. 1, Op.11 No.1 (1959), for piano",
"Jaan Rääts — Piano Sonata No. 3, Op.11 No.3 (1959), for piano",
"Jaan Rääts — Piano Sonata No. 4, Op.124 (2003), for piano",
"Jaan Rääts — Piano Sonata No. 9, Op.76 (1985; rev. 2014), for piano",
"Jaan Rääts — Piano Sonata No. 10, Op.114 (2000), for piano",
"Jaan Rääts — Prelude No. 4, Op.33 (1968), for piano",
"Jaan Rääts — Prelude, Op.128 (2014), for piano",
"Jaan Rääts — Sonata for Two Pianos, Op.82 (1990), for two pianos",
"Jaan Rääts — Toccata (1968), for piano",
"Jaan Rääts — Variations, Op.6 (1958), for piano",
"Jacopo Fachini — electroacoustic vocal intervention within Oleksandr Kutovyi's installation",
"James Joslin — Für Enola (2011) for toy piano, jack-in-the-box, and spinning top",
"James Tenney — Cellogram (1971) for cello",
"Isaac de Judea, Olga Ostroverkh, Pavlo Kosenko, Oleksiy Khokhun — Cante Chico: cante de fiesta in dialogue with the teachings of Rabbi Nachman of Breslov",
"Jean Catoire — Sonate n°19 Opus 520 (1990) for piano",
"Jeremy Wexler — Nystagmus (2018) for two violins and ensemble",
"Jeroen van Veen — Minimal Préludes 15, 17, 18, 21, 23 & 26 (1999–2003) for piano",
"Jo Kondo — Three Songs from the Elderberry Tree (1977; arranged for piano in 2010), for piano",
"Joanna Bailie — Artificial Environment No. 8 (2012–13) for piano and tape",
"Johann Sebastian Bach — Partita in G major, BWV 1006 (c. 1720) for violin solo",
"Johann Sebastian Bach / György Kurtág — Gottes Zeit ist die allerbeste Zeit (Actus Tragicus), BWV 106, transcription for piano four hands (1974)",
"Johann Strauss II / arr. Alban Berg — Wein, Weib und Gesang, Op. 333 (1921) for string quartet and piano",
"Johann Strauss II / arr. Anton Webern — Schatz-Walzer, Op. 418 (1921) for string quartet and piano",
"Johann Strauss II / arr. Arnold Schoenberg — Rosen aus dem Süden, Op. 388 (1921) for string quartet and piano",
"Johannes Eccard — O Lamm Gottes, unschuldig (c. 1597–1600) for five-part mixed choir a cappella",
"Johannes Maria Staud — Incipit (2000) for alto trombone and ensemble",
"Johannes Schöllhorn — Anamorphoses (2001–2004) for chamber ensemble",
"Johannes Schöllhorn — Conductus (2001) for clarinet, violin, cello, and piano",
"Johannes Schöllhorn — Dias, koloriert (2010) for chamber ensemble (drei neue Anamorphosen nach der Kunst der Fuge von J.S. Bach)",
"Johannes Schöllhorn — Madria (1994) for violin, cello, and button accordion",
"John Cage — 4′33″ (1952) for any instrument(s)",
"John Cage — 59½ Seconds for a String Player (1953) for solo string instrument",
"John Cage — Bacchanale (1940) for prepared piano",
"John Cage — Chorales (1974) for solo violin",
"John Cage — Dream (1948) for piano",
"John Cage — Dream (1948, arr. Margaret Leng Tan) for toy piano and grand piano",
"John Cage — Extended Lullaby (1992/1994, version by Margaret Leng Tan) for toy piano and tape",
"John Cage — Forever and sunsmell (1942) for voice and two percussion",
"John Cage — Hymnkus (1986) for indeterminate instrumentation",
"John Cage — In a Landscape (1948) for piano",
"John Cage — Quartet for Percussion (1935)",
"John Cage — Radio Music (1956), version for piano and radios",
"John Cage — Six Melodies (1950), Nos. 1, 4, 5, 6 for theremin and button accordion",
"John Cage — Six melodies: Pieces 1, 4, 6 (1950) for violin and piano",
"John Cage — Song No. 35 from Song Books (1970)",
"John Cage — Song No. 67 from Song Books (1970)",
"John Cage — Suite for Toy Piano (1948)",
"John Cage — Third Construction (1941) for four percussionists",
"John Kennedy — Fanfare from The Winged Energy of Delight (1997) for toy piano",
"John Lennon / Paul McCartney (arr. Toby Twining) — Eleanor Rigby (1966/2002) for toy piano and toy instruments",
"John Luther Adams — Nunataks (2007) for piano",
"John Palmer — Three Preludes (2013) for piano",
"John Psathas — Sleeper (2011) for piano",
"Jonathan Harvey — Tombeau de Messiaen (1994) for piano and tape",
"Jorge Campos — Glissando (2005) for theremin and tape",
"Jorge Sad Levi — Les Non Dupes Errent (2008) for saxophone",
"Joseph Kudirka — Wyoming Snow (2007–08) for ensemble",
"José María Sánchez-Verdú — Scriptvra Antiqva (Madrigalbuch I) (2010–2012) for five solo voices, a cappella",
"Julia Wolfe — Compassion (2001) for piano",
"Julia Wolfe — Earring (2000) for piano",
"Julius Eastman — Piano 2 I/II/III (1985–1986) for piano",
"Jörg Widmann — Liebeslied (2010) for eight musicians",
"Jürg Frey — Les tréfonds inexplorés des signes #5 (2007–2009) for piano",
"Jānis Petraškevičs — Kārtības rituāli (\"Rituals of Order\") (2021/2022) for violin, viola, cello, piano",
"Kaija Saariaho — Ballade (2005) for piano",
"Kaija Saariaho — Mirrors (1997) for flute and cello",
"Kaija Saariaho — Prelude (2007) for piano",
"Karlheinz Stockhausen — Capricorn (1977) from Sirius, for bass voice and electronic music",
"Karlheinz Stockhausen — Kontra-Punkte (1952–1953) for ten instruments",
"Karlheinz Stockhausen — Tierkreis (Zodiac), 12 melodies of the star signs (1974–75), version for bass voice and music boxes",
"Karmella Tsepkolenko — Solo–Solissimo No. 2 (2002) for piano (right hand)",
"Karol Nepelski — Trio of Forgotten Senses (2007) for flute, violin, and piano",
"Katya Buchatska — Lethe (2018), audiovisual installation",
"Kazuki Tomokawa — The Voice of the Screaming Soul (2016), for voice and acoustic guitar, solo live",
"Kenji Sakai — Initial S (2010) for alto saxophone solo",
"Kirill Chernegin — Untitled IX (2015), version for vocal ensemble",
"Klaus Huber — In nomine – ricercare il nome (1999) for six instruments",
"Klaus Lang — Die Wimpern des himbeerfarbenen Mondes / Marienau (1996/1997) for vocal ensemble",
"Konstantia Gourzi — ...il vento del nord... (2012–2013) for ensemble",
"Konstantia Gourzi — Hommage à Kurtág (1995) for voice and cimbalom",
"Konstantia Gourzi — Beauty (2017) for ensemble",
"Kristina Megyeri — Jeux-en-jeux (2006) for eight musicians",
"Kyle Gann — Going to bed (1994) for piano",
"La Monte Young — X For Henry Flynt (1960) for piano",
"Laurence Crane — Piano Piece 23: Ethiopian Distance Runners (2009) for piano",
"Laurence Crane — Raimondas Rumsas (2002) for cello with Bach-bogen",
"Laurence Crane — Trio for Ros and Peter (2003) for bass flute, clarinet, and piano",
"Lawrence Ball — Piano Suite No. 8 (2014)",
"Leonardo Marino — Concerto per pianoforte e ensemble (2017)",
"Leonardo Marino — L'artificio del fuoco (2019) for violin, cello and large ensemble",
"Leonid Hrabovsky — Microstructures (1964/1975) for solo oboe",
"Leonid Hrabovsky — Ornaments (1969/1987) for oboe, viola, and harp",
"Leonid Hrabovsky — To Elise, in Memory (1988) for piano — to Elissa Stutz",
"Leoš Janáček — Sonata 1.X.1905 (1905) for piano",
"Lepo Sumera — Two pieces from the year 1981: n. 1 (1981) for piano",
"Liis Viira — Nova Vision (2014) for piano",
"Lisa Biletska — Medea in the Gardens of the Hesperides (2023), digital diptych",
"Louis Andriessen — Symphony of Open Strings (1978) for twelve string instruments",
"Louis Andriessen — Triplum (1962) for guitar",
"Louise Bourgeois — Insomnia Drawing (1994–95 / musical realisation 2018–19), open-score graphic work for flexible ensemble",
"Luca Antignani — Barche amorrate (2012) for five voices",
"Luca Antignani — Due Interludi (2008–2011) for cimbalom",
"Luca Antignani — Cosa Arcana (2017) for ensemble",
"Luca Antignani — …ed il mare rispose in eco (2003) for voice, choir and ensemble",
"Luca Francesconi — Secondo concerto per oboe (1991)",
"Luca Francesconi — Viaggiatore insonne (1983) for soprano and five instruments",
"Lucia Ronchetti — Blumenstudien. Madrigale a cinque voci (2012)",
"Luciano Berio — Chemins II (1967) for viola and ensemble",
"Luciano Berio — O King (1968) for soprano, flute, clarinet, violin, cello, and piano",
"Luciano Berio — Points on the Curve to Find… (1974) for piano and chamber orchestra",
"Luciano Berio — Quattro canzoni popolari (1947) for voice and piano",
"Luciano Berio — Sequenza I (1958) for solo flute",
"Luciano Berio — Sequenza III (1965) for female voice",
"Luciano Berio — Sequenza XIII (\"Chanson\") (1995) for accordion",
"Ludmila Yurina — Drift (2014) for string orchestra, piano, and percussion",
"Ludmila Yurina — Lady Lazarus (2014–2015) for soprano and piano, based on poems by Sylvia Plath and James Joyce",
"Ludmila Yurina — Silicon Interferences (2015) for flute, clarinet, piano, violin, and cello",
"Luis Naón — Ex Lex (2012) for seventeen instruments",
"Luiz Henrique Yudo — 5 Palindromes (2011) for flexible ensemble",
"Lukas Ligeti — Passacaglia with Variations (2016) for trio",
"Lukas Tobiassen — Dröhnen, überzuckert (2017) for bass clarinet and ensemble",
"Lydia Ayers — The Art of Stone in a Dreamworld (1999) for theremin and electronics",
"Lydia Kavina — Constellations (1999–2000) for theremin and button accordion",
"László Sáry — Mindig csak az van, ami van (2016) for trio",
"Maksym Ivanov — Shades of White No. 2 (April 2023) for clarinet, crotales, and cello",
"Marcel Duchamp — Erratum Musical (1913)",
"Mariana Sadovska — Chornobyl. The Harvest (2013) for voice, harmonium, and string quartet",
"Mariana Sadovska — Odessa Underground: Songs from the repertoire of Alexander Vertinsky, Kurt Weill, and others (2012) for voice and piano",
"Marion Sinclair — Kookaburra sits in the old gum tree (1932)",
"Mark-Andreas Schlingensiepen — Cosa arcana e stupenda (2017) for ensemble",
"Matteo Gualandi — Le strade e le vene (2018) for trumpet, trombone, horn and ensemble",
"Matthew Shlomowitz — Popular Contexts 2 (2010) for piano, sampler, voice and physical actions",
"Maurice Ohana — Preludes Nos. 12 & 13 (1971) for piano",
"Maurice Ohana — Étude \"Fifths\" (1964)",
"Maurice Ohana — Étude \"Free Cadenzas\" (1961)",
"Mauro Lanza — Disiecta Membra (2014–2015) for six voices, a cappella",
"Mauro Lanza — Mare (2006) for voice, ensemble and toy instruments",
"Maxim Kolomiiets — Re-pulse (2012) for oboe and button accordion",
"Maxim Kolomiiets — Empty Pedestals (2010) for flute, clarinet, cello, and piano",
"Maxim Kolomiiets — Paths of the Rejected: four movements from the cantata (2015), for female choir, solo soprano, and chamber orchestra",
"Maxim Kolomiiets — I Saw Your Reflection in the River's Mirror. You Were on the Other Side (March 2022) for bandura solo",
"Maxim Kolomiiets — Vinyl Snails (2016) for flute, clarinet, vibraphone, piano, violin, cello",
"Maxim Kolomiiets — Prolegomena to an Opera: Songs for Kyiv Mohyla Academy (2025) to the texts by Sasha Andrusyk, for three singers and ensemble",
"Maxim Shalygin — Agnus Dei (2009, from Songs of Holy Fools)",
"Maxim Shalygin — Letters to Anna: Symphony (2008–2011) for solo violin",
"Maxim Shalygin — When Everything Ends, We Start to Sing Our Songs (2012) for tape/fixed media",
"Melaine Dalibert — Ballade (2014) for piano",
"Melaine Dalibert — Cortège (2011) for piano",
"Melaine Dalibert — Gruppetto (2013) for piano",
"Melaine Dalibert — Variations (2014) for piano",
"Meredith Monk — Atlas: An Opera in Three Parts (1991), selected pieces",
"Michael Finnissy — Above Earth's shadow (1985) for violin and ensemble",
"Michael Finnissy — Choralevorspiele I–III (1994) for piano",
"Michael Jarrell — Bebung (1995) for solo clarinet, solo cello, and ensemble",
"Michael Jon Fink — 5 piano pieces (1997)",
"Michel van der Aa — Transit (2009) for piano, electronics and video projection",
"Michele Del Prete — E fu giorno (2013)",
"Jacopo Facchini, Michele Foresi — Site-responsive piece for Sasha Kutovyi's A Good Man Hard to Find (2017), for voice and electronics",
"Mihkel Kerem — Piano solo from Nimeta Lood (2007)",
"Mihkel Kerem — Prelüüd Nr. 9, 11, 12, 13, 14, 15, 16 (2008)",
"Miklós Kocsár — Kassák-dalok (1978) for voice, flute, and cimbalom",
"Miloš Rajković — Waiting for C-A-G-E (2012) for toy piano",
"Mkhitar Ayrivanetsi — liturgical monody (c. 1235–1297/1300)",
"Monk of Salzburg — Martin, lieber Herre (14th c.)",
"Montpellier Codex — Alle psallite cum luya (13th c.)",
"Montpellier Codex — Amor potest conqueri (13th c.)",
"Montpellier Codex — Huic ut placuit (13th c.)",
"Morteza Shirkoohi — Arteeman (2014)",
"Morton Feldman — Durations IV (1961) for violin, cello, and vibraphone",
"Morton Feldman — Extensions 3 (1952) for piano",
"Morton Feldman — Intermission 5 (1952) for piano",
"Morton Feldman — Intermission 6 (1953) for piano",
"Morton Feldman — Nature Pieces II, III (1951) for piano",
"Morton Feldman — Palais de Mari (1986) for piano",
"Morton Feldman — Piano Piece [to Philip Guston] (1963) for piano",
"Morton Feldman — Rothko Chapel (1971) for soprano, alto, mixed choir and instruments",
"Morton Feldman — Variations (1951) for piano",
"Morton Feldman — Vertical Thoughts 4 (1963) for piano",
"Morton Feldman — Voices & Instruments 1 (1972) for mixed choir and instruments",
"Morton Feldman — Voices & Instruments 2 (1972) for three female voices and instruments",
"Mykhailo Chedryk — Sonare (2023) for double bass solo",
"Naftali Schindler — Norfolk in Summer (2011) for toy piano and glockenspiel",
"Natalia Cherniy — Melancholy (2011) for violin, cello, and piano",
"Natalia Pschenitschnikova — The Well. The Voice of Memory (2014–2016), fragments",
"Natalia Pschenitschnikova — Voice of Zangezi (2018), mono-opera set to a text by Velimir Khlebnikov, for soprano and electronics",
"Natalia Pschenitschnikova — Walks Nos. 1–2 (2004) for voice and electronics",
"Nazar Stets — Sira Zemlia (2022) for double bass solo",
"Nemanja Lakicevic — Concerto for violin and ensemble (2017)",
"Newton Armstrong — making one leaf transparent and then another (2012) for piano",
"Niccolò Castiglioni — Momenti musicali (1992) for seven instruments",
"Nick Roth, Olesya Zdorovetska, Fulvio Sigurtà, Alex Roth, Jack McMahon — .AVI: I (2015), audiovisual improvisation with live drawing by Jenya Tchaikovska",
"Nicole Lizée — Death to Kosmische (2010) for string quartet, vintage electronics and track",
"Oleh Shpudeiko (Heinali), Volodymyr Shpudeiko — Synthtap performance using modular synthesis (2017)",
"Oleh Shpudeiko (Heinali) — Kyiv Eternal (2023), audiovisual installation with visuals by Kachna Baraniewicz and Maryna Osnach",
"Oleksandr Shymko — Chronos (2012) for vocal ensemble and chamber orchestra",
"Alex Voytenko — The Music of Erich Zann (2010; rev. 2017) for double bass solo",
"Olena Serova — You Can Feel (2012) for flute, clarinet, horn, cello, and piano",
"Olivier Messiaen — Le Merle noir (1951) for flute and piano",
"Olivier Messiaen — Louange à l'Éternité de Jésus (1940–1941) for cello and piano",
"Olivier Messiaen — Oiseaux exotiques (1955–1956) for solo piano and small orchestra",
"Omar Souleyman (arr. Jacob Garchik) — La Sidounak Sayyada for string quartet",
"Oscar Bianchi — Ante Litteram (2011–2013) for six voices a cappella",
"Oskar Carmona — Cygnus X-1 (2011) for piano and magnetic tape",
"Ostap Manulyak — A quick glance at landscape (2015) for flute, clarinet, percussion, piano, and cello",
"Ostap Manulyak — Reprogression 2 (November 2022), live electronics",
"Ostap Manulyak — Three Songs (2008) for soprano, flute, clarinet, violin, cello, piano, and electronics",
"Pascal Dusapin — Coda (1992) for thirteen instruments",
"Paul Hindemith — Messe für gemischten Chor a cappella (1963)",
"Peter Ablinger — Erzsébet \"Kokó\" Kukta (2015) for piano and recording",
"Peter Cusack — Sounds from Dangerous Places (2012), audioinstallation",
"Phil Minton, Audrey Chen — Site-responsive vocal improvisation (2015, Museum of Natural History, Kyiv)",
"Philip Glass — 1+1 (1968) for piano",
"Philip Glass — 600 Lines (1967) for piano",
"Philip Glass — A Musical Portrait of Chuck Close (2005) for piano",
"Philip Glass — Candyman (1992) for piano",
"Philip Glass — Dreaming Awake (2003) for piano",
"Philip Glass — Etudes No. 3, 5, 6, 8, 9 (1994–1995) for piano",
"Philip Glass — How Now (1968) for piano",
"Philip Glass — Jenipapo: No. 14 (1995) for piano",
"Philip Glass — Mad Rush (1979; rev. 1981) for piano",
"Philip Glass — Metamorphosis I–V (1988) for piano",
"Philip Glass — Modern Love Waltz (1977) for piano",
"Philip Glass — Monsters of Grace — Epilogue (1998/arr. 2001) for piano",
"Philip Glass — Music in Contrary Motion (1969) for piano",
"Philip Glass — Music in Fifths (1969) for piano",
"Philip Glass — No Reservations (2007) for piano",
"Philip Glass — Notes on a Scandal (2006) for piano",
"Philip Glass — Opening (1982) for piano",
"Philip Glass — Opening from Glassworks (1981) for piano",
"Philip Glass — The Fog of War (2002/arr. 2003) for piano",
"Philip Glass — The Hours (2002/arr. 2003) for piano",
"Philip Glass — The Olympian: Lighting of the Torch (1984) for piano",
"Philip Glass — The Orphée Suite (1991/arr. 2000) for piano",
"Philip Glass — The Screens (1989/arr. 1991) for piano",
"Philip Glass — The Truman Show (1998) for piano",
"Philip Glass — Trilogy Sonata (2000) for solo piano",
"Philip Glass — Two Pages (1968) for piano",
"Philip Glass — Violin Concerto No. 2 \"The American Four Seasons\" (2009) for violin and orchestra",
"Philip Glass — Wichita Vortex Sutra (1988) for solo piano",
"Philip Glass — Études for Piano (1994–2012), Books I–III",
"Phyllis Chen — Cobwebbed Carousel (2010) for toy piano and music box",
"Pierre Bastien — Playing with the Dead (2014), live performance for self-built mechanical instruments, trumpet, and video",
"Pierre Bastien — Résurrectine (2012) for self-built mechanical instruments, nail violin, trumpet, and video, after Locus Solus by Raymond Roussel",
"Pierre Boulez — Dérive 1 (1984) for flute, clarinet, vibraphone, piano, violin, cello",
"Pierre Boulez — Dérive 2 (1988) for eleven instruments",
"Pierre Boulez — Improvisation sur Mallarmé I (1959) for soprano, five percussionists, and harp",
"Péter Eötvös — Molto tranquillo (Kurtág 90) (2015) for trio",
"Pēteris Vasks — Message (Vēstījums) (1982) for strings, percussion, and two pianos",
"Pēteris Vasks — Viatore (2001) for string orchestra",
"Quentin Lauvray — Effacements…résiliences (2018) for English horn, horn, cello and ensemble",
"Ram Narayan (arr. Kronos) — Raga Mishra Bhairavi: Alap",
"Raminta Šerkšnytė — De Profundis (1998) for string orchestra",
"Rebecca Saunders — Fury II (2009) for solo double bass and ensemble",
"Robert Ashley — She Was a Visitor (1967) for solo speaker and chorus",
"Robert Schumann — Du bist wie eine Blume, Op. 25 No. 1 (1840) for cello and piano",
"Rodrigo Bussad — Pálido (2017) for marimba and ensemble",
"Roman Haubenstock-Ramati — Alone II (1969) for ensemble",
"Ruth Wiesenfeld — Soffocato (2013) for five voices",
"Ruth Wiesenfeld — Oscuro (2016) for large ensemble",
"Ryan Carter — Errata (2010)",
"Régis Campo — Mysterium Simplicitatis (2014)",
"Salvatore Sciarrino — Anamorfosi (1993) for piano",
"Salvatore Sciarrino — Archeologia del telefono (2005) for thirteen instruments",
"Salvatore Sciarrino — De la nuit (1971) for piano",
"Salvatore Sciarrino — Esplorazione del bianco I (1986) for double bass",
"Salvatore Sciarrino — Introduzione all'oscuro (1981) for twelve instruments",
"Salvatore Sciarrino — Lo spazio inverso (1995) for piano",
"Salvatore Sciarrino — Luci mie traditrici (1998), opera in two acts; libretto by the composer after G. A. Cicognini (1664), for four solo voices and chamber orchestra",
"Salvatore Sciarrino — Perduto in una città d'acque (1990–91) for piano",
"Salvatore Sciarrino — Sei capricci (1975–76) for solo violin, movements I, II, VI",
"Salvatore Sciarrino — Vanitas. Natura morta in un atto (1981), mono-opera for mezzo-soprano, cello, and piano",
"Salvatore Sciarrino — Vento d'ombra (2005) for thirteen musicians",
"Samuel Andreyev — Iridescent Notation (2012–17), cantata for soprano and ensemble",
"Samuel Andreyev — Le malheur adoucit les pierres (2002) for bass flute, English horn, bassoon",
"Samuel Andreyev — Lighting Up (2016) for double bass",
"Samuel Andreyev — Nets Move Slowly, Yet (2006–07) for ensemble",
"Samuel Andreyev — Night Division (2008–10) for alto flute, English horn, clarinet, trombone, piano, percussion, double bass",
"Samuel Andreyev — Sextet in Two Parts (2019) for ensemble",
"Samuel Andreyev — Cosa arcana e stupenda (2017) for ensemble",
"Samuel Andreyev — À propos du concert de la semaine dernière (2013) for piano and 7 instruments",
"Samuel Andreyev — Événements quotidiens (2011) for ensemble",
"Katya Libkind, Sasha Andrusyk — Bad Trips (Everyday) — A Collective Exhibition with Mothers (performative intervention)",
"Sergei Zagny — Sonata (1990) for piano (with video by Francesca Piovano)",
"Serhii Piliutykov — Sfumato (2013) for button-accordion and chamber orchestra",
"Silvana Torto — quasi un madrigale... (2013) for five voices",
"Silvia Colasanti — Logica in fiamme (2008) for piano",
"Silvia Colasanti — Ombre del bianco (2002) for piano",
"Simeon ten Holt — Canto Ostinato (1976–1979) for piano",
"Sofia Gubaidulina — Aus den Visionen der Hildegard von Bingen (1994) for alto",
"Sofia Gubaidulina — De profundis (1978) for solo button accordion",
"Stanislav Kreichi — Immersion (1976) for theremin and ANS synthesizer",
"Stefano Gervasoni — Animato (1992) for eight instruments",
"Stefano Gervasoni — Dodici sonetti di Camões (2007–09/2017) for baritone and large ensemble",
"Stefano Gervasoni — Due poesie francesi di Rilke (1995–1996) for female voice, flute, clarinet, percussion, piano and string quartet",
"Stefano Gervasoni — Due Preludi (2008–2010) for piano",
"Stefano Gervasoni — Fuga ante mortem (2013) for five voices",
"Stefano Gervasoni — Lilolela (1994), Vagabonderia severa for 23 musicians",
"Stefano Gervasoni — Pas perdu (2014) for cimbalom solo",
"Stefano Gervasoni — Prés I, II & III (2008–2015) for piano",
"Stefano Gervasoni — Strepito e garbuglio (2005/2015) for double bass",
"Stefano Gervasoni — Limbus Limbo (2012), apéro bouffe for four singers, ensemble, and electronics",
"Stefano Scodanibbio — Sei studi (1981–1983) for double bass",
"Stephen Montague — Mirabella (A Tarantella) (1995) for toy piano",
"Steve Reich — Music for 18 Musicians (1976)",
"Steve Reich — WTC 9/11 (2010) for string quartet and pre-recorded audio",
"Steven Kazuo Takasugi — Die Klavierübung I (2007–09/2014) for piano and tape",
"Sven-Ingo Koch — Simple Songs & Songs of Pining (2021-2022) for voice and piano, set to poems by Jan Wagner",
"Svitlana Azarova — Chronometer (2004) for piano solo",
"Svyatoslav Lunyov — Bad Tempered Songs (1994), mono-opera for voice and chamber orchestra, to texts by Lewis Carroll",
"Svyatoslav Lunyov — Melancholy (2011) for piano and electronics",
"Svyatoslav Lunyov — The Noel Consort (2013–2014), concerto for mixed choir based on traditional carols",
"Svyatoslav Lunyov — from Mardongs (1992–2004) for piano: Mardongs 1, Anonim XIV",
"Takashi Yoshimatsu — Atom Hearts Club Suite No. 2, Op. 79A (1999) for string orchestra",
"Takashi Yoshimatsu — While an Angel Falls into a Doze, Op. 73 (1998) for strings and piano",
"Terry Jennings — 1950 Piece (1950) for piano",
"Terry Jennings — Piano Piece for Christine (1960) for piano",
"Terry Jennings — Winter Sun (1960) for piano",
"Terry Jennings — Winter Tree (1960) for piano",
"Terry Riley — In C (1964) for eighty musicians",
"Terry Riley — Keyboard Studies (1965) for piano",
"Thomas Ravenscroft — Come Drink to Me (1609)",
"Tiziano Manca — Stur (2007–2010) for guitar",
"Toby Twining — An American in Buenos Aires (A Blues Tango) (2001) for toy piano",
"Tomasz Kamieniak — Nuits à Paris op. 53 (2014) for piano",
"Tomomi Adachi, Hannah Silva — Pluto is a planet! (2018), live performance for voice, electronics, sensor-based interaction and a participatory choir",
"Toru Takemitsu — Itinerant: In Memory of Isamu Noguchi (1989) for flute",
"Toru Takemitsu — Rain Coming (1982) for ensemble",
"Toru Takemitsu — Tree line (1988) for chamber orchestra",
"Toshio Hosokawa — Drawing (2004) for flute, oboe, clarinet, percussion, piano, violin, viola, cello",
"Toshio Hosokawa — Im Frühlingsgarten (2002) for nine musicians",
"Toshio Hosokawa — Singing garden (2003) for six musicians",
"Toshio Hosokawa — Twill (Aya-Ori) (2016) for trio",
"Toshio Hosokawa — Voyage V (2001) for flute and chamber orchestra",
"Tristan Murail — Legendes urbaines (2006) for twenty instruments",
"Tristan Murail — Vampyr! (1984) for electric guitar",
"Tze Yeung Ho — Ring dem som (sk)river postkort og si at blekket har tørket (2018) for English horn, violin and ensemble",
"Nick Roth, Olesya Zdorovetska, Lauren Kinsella, Simon Roth, Mark Tokar — Happy New Ears (2012), a live improv",
"Dmytro Radzetsky, Ukrainian Improvisers Orchestra — .AVI II (2015), a live improv with contingent scenography by Katya Libkind and Olga Gaidash",
"Valentyn Silvestrov — Elegy (1967) for piano",
"Valentyn Silvestrov — Five Pieces (1961) for piano",
"Valentyn Silvestrov — Icon (2004) for strings",
"Valentyn Silvestrov — Maidan 2014, choral cantata",
"Valentyn Silvestrov — Music of Silvery Tones (3 pieces) for piano — to Halyna Mokreieva",
"Valentyn Silvestrov — Postludium for cello and piano",
"Valentyn Silvestrov — Projections (1965) for harpsichord, vibraphone, and bells",
"Valentyn Silvestrov — Quartetto piccolo (1961) for strings",
"Valentyn Silvestrov — Serenade (3 pieces) for piano — to Larysa Bondarenko",
"Valentyn Silvestrov — Silent Songs (1974–1977) for voice and piano",
"Valentyn Silvestrov — Songs (Піснеспіви) to the poems by Taras Shevchenko (2014) for mixed choir",
"Valentyn Sylvestrov — String Quartet No. 1 (1974)",
"Valentyn Silvestrov — String Quartet No. 3 (2011)",
"Valentyn Silvestrov — Stufen (Steps) (1980–82/1997) for soprano and piano",
"Valentyn Silvestrov — Symphony No. 2 (1965) for flute, timpani, piano, and string orchestra",
"Valentyn Silvestrov — The Messenger — Year 1996 (1996–97) for piano — to Larysa Bondarenko",
"Valentyn Silvestrov — Triad (1962/1966) for piano",
"Valentyn Silvestrov — Trio (1962) for flute, trumpet, and celesta",
"Valentyn Sylvestrov — Cantata on Poems by F. Tyutchev and A. Blok (1973) for soprano and ensemble",
"Valentyn Sylvestrov — Children's Music No. 1 (1973) for piano",
"Valentyn Sylvestrov — Drama: Sonata (1970) for violin and piano",
"Valentyn Sylvestrov — Five plays for piano (1961)",
"Valentyn Sylvestrov — Forest Music (1977–1978) for soprano, horn, and piano — on poems by Gennadiy Aygi",
"Valentyn Sylvestrov — Kitsch-Music (1977) for piano",
"Valentyn Sylvestrov — Music in the Olden Style (1973) for piano",
"Valentyn Sylvestrov — Mystery (1964) for alto flute and six groups of percussion",
"Valentyn Sylvestrov — Piano Sonata No. 2 (1975)",
"Valentyn Sylvestrov — Piano Sonata No. 3 (1979)",
"Valentyn Sylvestrov — Projections (1965) for harpsichord, vibraphone and tubular bells",
"Valentyn Sylvestrov — Seven Pieces (June–July 2022) for piano",
"Valentyn Sylvestrov — Sonata 2 (1975) for piano",
"Valentyn Sylvestrov — Three Pieces (April 2022) for piano",
"Valentyn Sylvestrov — Three Pieces (March 2022) for piano",
"Vasyl Tkachenko — In dialogue with Nazar Stets (2024), visual project (painting and video)",
"Victoria Poleva — Ars Moriendi: 18 songs for an actor who sings (1983–2012) for voice and piano",
"Victoria Poleva — Ave Maris Stella (2014) for choir a cappella",
"Victoria Poleva — Gagaku: Tadashi Endo's solo butoh performance to the recording of the piece (2012)",
"Victoria Poleva — Lullaby (2002) for piano",
"Victoria Poleva — Music for Flute, Strings, and Percussion (1986)",
"Victoria Poleva — Null (2005) for button accordion",
"Victoria Poleva — Summer Music (2008) for violin, chamber orchestra, and children's choir",
"Victoria Poleva — The blind hand (2013) for theremin and button accordion",
"Victoria Poleva — Trivium (2007) for piano",
"Victoria Poleva — Warm Wind (2008) for vibraphone and chamber orchestra",
"Vidmantas Bartulis — The Third Express (2003) for violin, piano, and strings",
"Viktor Marushchenko — Valentyn Silvestrov: An adjacent frame (2017), documentary installation built from previously unseen footage",
"Vitaliy Hodziatsky — Autographs (1962–63) for piano",
"Vitaliy Hodziatsky — Characteristic Scenes [Autographs] (1963/1985) for piano",
"Vitaliy Hodziatsky — Four Études for Tape (1964)",
"Vitaliy Hodziatsky — Prelude in G-sharp minor (1961) for piano",
"Vitaliy Hodziatsky — Rupture of Surfaces (1963) for piano",
"Vitaliy Hodziatsky — Seven Character Scenes (1963/1985) for piano",
"Vitaliy Hodziatsky — Sonata No. 2 (1973) for piano",
"Vitaliy Hodzyatsky — Sonata No. 3 (1962 / 2022) for piano",
"Vitaliy Hodziatsky — String Quartet No. 2 (2014)",
"Volodymyr Huba — Three Sketches (1962) for piano — to Halyna Mokreieva",
"Volodymyr Rudenko — Creation (Tvorennia) (May 2023) for bass clarinet, gongs, cello, and double bass",
"Volodymyr Zahortsev — Game of Refrains. Piano Sonata No. 2 (1970–71; rev. 1999)",
"Volodymyr Zahortsev — Rhythms (first version, 1967) for piano",
"Volodymyr Zahortsev — Rhythms (second version, 1969) for piano",
"Volodymyr Zahortsev — Three Epitaphs (1998) for piano",
"William Byrd — John, Come Kiss Me Now (late 16th–early 17th c.)",
"William Susman — Quiet Rhythms Book I: Prologue 3/4/5/6 Prologue + Action 7/8 (2010)",
"Ying Wang — Illuminations (2022) for piano, voice, and electronics",
"Yurii Bulka — DjinaImpro (2003) for flute, electronics, and recitation ad libitum",
"Yuriy Samson — Inmostones (March 2023) for live electronics",
"Zad Moultaka — Zourna (2007) for saxophone",
"Zoltan Almashi — Van Gogh (2011) for kitchen utensils",
"Šarūnas Nakas — Aporia (2001) for three instrumental groups",
"Šarūnas Nakas — Icon of Fire (2008) for chamber ensemble",
"Šarūnas Nakas — Kitman. Homage to Czesław Miłosz (2012) for piano",
"ujif_notfound — TER.RAIN (June 2023) LIVE",
"ujif_notfound, Alisa Haspyd, Yevhen Ulianov — Lotto-cola, Mid-Devourers, and Other Stories in the Dark (2024), live electroacoustic performance based on texts by Halyna Tkachuk"
];
